### ISSUE TITLE
右键托盘菜单位置奇怪

### ISSUE THREAD

**Issue by Gabirel** [Yufeikang/bcloud#15]
## 系统环境
- Arch Linux
- XFCE4

## 期望行为
菜单位置应该在鼠标当下，而不是左侧

## 实际效果
![screenshot_2017-05-15_14-13-49](https://cloud.githubusercontent.com/assets/12933851/26044895/b8396210-3979-11e7-9ca5-21b004792c0e.png)

**Comment by Yufeikang** [comment]
ubuntu平台下是正常的，arch linux还没有用过，界面不是我写的，时间有限我目前之维护一些功能没问题。如果有时间欢迎pull request

**Comment by Gabirel** [comment]
REF: https://github.com/Yufeikang/bcloud/blob/master/bcloud/App.py#L412
