### ISSUE TITLE
下载列表中的文件，就算暂停也无法删除任务

### ISSUE THREAD

**Issue by dickzhenhua** [Yufeikang/bcloud#2]
下载列表中的文件，就算暂停了也无法删除任务，希望增加这个功能，如果下载错文件了，比如是一个几G的视频文件，非要等到下载完毕才能删除的话，强迫症会发作。。。

**Comment by yinflying** [comment]
表示可以remove任务，不存在这个问题。

**Comment by dickzhenhua** [comment]
@Yufeikang 使用别人打包好的deb是这样的情况，无法删除没有下载完毕的任务（右键无菜单出来），然后#sudo python3 setup.py安装报错，使用#sudo python3 setup.py install安装成功（以上详细情况均在https://bbs.deepin.org/forum.php?mod=viewthread&tid=137073，使用的系统是deepin15.3，基于Debian的），但是无法运行，请出个在LINUX下的完整安装步骤可以吗？万分感谢。

**Comment by Yufeikang** [comment]
@dickzhenhua 谢谢提醒， 安装确实是 sudo python3 setup.py install 一开始就写错了，一直没改
