### ISSUE TITLE
下载任务的取消

### ISSUE THREAD

**Issue by zyiii12** [Yufeikang/bcloud#26]
选择了一个大文件的下载，反悔了想取消，怎么都没找到在哪里取消，强迫症只好手动改tasks.sqlite......
想问一下这个取消选项是界面上本来就没有吗？还是说我眼瞎了......

**Comment by wkcn** [comment]
程序的右上角有一个“-”按钮，即删除选中的任务。
不过现在不能直接在任务上右键操作，还是有点不方便。

**Comment by zyiii12** [comment]
@wkcn 还真是我眼瞎了...谢谢

**Comment by wkcn** [comment]
@zyiii12 不客气～
