### ISSUE TITLE
請問 Arch 的 AUR 有機會看到這個版本的 Bcloud 嗎？

### ISSUE THREAD

**Issue by JulianLai** [Yufeikang/bcloud#3]

**Comment by youyiqin** [comment]
请问怎么安装呢，我得到deb包用dpkg安装失败。

**Comment by Yufeikang** [comment]
应该是可以的，你安装试试 python3 setup.py install

**Comment by francistw** [comment]
直接下載 https://aur.archlinux.org/packages/bcloud-git/ 的 PKGBUILD，再將裏面的 https://github.com/LiuLang/bcloud 改為 https://github.com/Yufeikang/bcloud 應該就行了

**Comment by JulianLai** [comment]
@francistw 成功了，不過還是希望能夠在 AUR 中直接載到，有辦法讓它取代原本的 bcloud-git 嗎？

**Comment by francistw** [comment]
@JulianLai 這你得聯絡它的維護者了，問他能不能換成這個源。不然就得打包 bcloud-Yufeikang-git 之類的上傳到 AUR 自己當維護者。

**Comment by JulianLai** [comment]
@francistw 成功了

**Comment by francistw** [comment]
@Yufeikang 那這個 issue 就解決了
