### ISSUE TITLE
bcloud不能登录

### ISSUE THREAD

**Issue by jingle0927** [Yufeikang/bcloud#40]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=141734&extra=

deepin@deepin:~$ bcloud-gui 

** (bcloud-gui:5194): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(bcloud-gui:5194): Gtk-WARNING **: (/build/gtk+3.0-NmdvYo/gtk+3.0-3.22.11/./gtk/gtkicontheme.c:2184):gtk_icon_theme_choose_icon: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
2017-06-29 08:55:09,803 gutil.py :118 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/lib/python3/dist-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found

2017-06-29 08:55:09,804 SigninDialog.py :97 ERROR SigninVcode.refresh_vcode: None, Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/lib/python3/dist-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found
.
2017-06-29 08:55:26,187 SigninDialog.py :365 ERROR SigninDialog.on_post_login: (400037, None), None
deepin@deepin:~$

**Comment by Yufeikang** [comment]
错误码400037 似乎你的帐号出了问题

**Comment by JulianLai** [comment]
@Yufeikang 無法登入
(bcloud-gui:7752): Gtk-WARNING **: (gtkicontheme.c:2184):gtk_icon_theme_choose_icon: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:243:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:250:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:261:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:268:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:279:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:286:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:302:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:312:62: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:316:73: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1481:71: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1530:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1547:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1552:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1565:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:1570:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2002:73: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2015:62: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2021:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2206:62: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2214:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2220:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2745:11: Not using units is deprecated. Assuming 'px'.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:2745:11: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3347:35: '-gtk-gradient' is not a valid color name

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3682:53: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3721:53: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3725:59: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3731:53: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:3731:87: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4073:10: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4073:19: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4489:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4855:73: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4865:62: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4869:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4879:54: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4965:60: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4980:67: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4984:56: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:4996:62: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5201:10: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5201:22: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5221:37: 'linear-gradient' is not a valid color name

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5233:10: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5233:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5236:10: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5236:30: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5239:10: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5239:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5256:14: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5256:14: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5263:14: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5263:14: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5272:16: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5272:16: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5277:16: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5277:16: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5354:14: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5357:16: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5357:16: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5409:14: not a number

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5409:14: Expected a string.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5412:68: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5642:74: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5652:62: Using one color stop with linear-gradient() is deprecated.

(bcloud-gui:7752): Gtk-WARNING **: Theme parsing error: gtk-dark.css:5656:73: Using one color stop with linear-gradient() is deprecated.
2017-06-29 11:51:23,504 SigninDialog.py :345 ERROR SigninDialog.on_post_login: (120021, {'err_no': 120021, 'callback': 'parent.bd__pcbs__28g1kg', 'codeString': 'njGe206de7bcc49f5e8023f141da6013e00b7595b0684018ac3', 'userName': 'user@hotmail.com', 'u': 'http://www.baidu.com/', 'secstate': 'PA000', 'authtoken': 'cb29iLTVaiiMMIzA/YoqNWIEyZA/58xIECwws93JdX9cAttpV34WJcUbCweVOwuszglrlr6kJvG05QBwwZFz3Maxfhn449PMDnhd9y4/qJFFXp02u+t468A+XHaIW0ixh4mGUE+FyiBR+yC0RLlWozDExYugRW6c+3ECnYK4apqqqdUEjtrbdkCJCrP4IuECYey6TfSzeqG7R41ER1Px1WAAr8uO3e158tsb+AfDGpttuz6eDaaHPCWTd+Vplo2MpfLs4sOnT+UNqafflwUH0e+ibboRBtZhTGllIovYlifEswN44IzF8ObB+dqgHtNWKpHHjfCxgWvDIsXbb0u9WqDbh2gDV9Y', 'loginproxy': 'https://passport.baidu.com/v2/?loginproxy&u=http%3A%2F%2Fwww.baidu.com%2F&tpl=&ltoken=246c852f8a86519e52f90ff8728cc11e&lstr=297d9TOOY4f%2Fa3FCsZg%2BkICVwpXav1%2BWz55bi6%2B0MN96Pv2pZEsnpSgz8QSL1QQIoDYHGn3B5qsVrw9o0KRt', 'vcodetype': '158cIXZX26KoeVtjCInR\\/HzyNmljiAqaNG5qK9mBkP6jgugmzMWMOB9TDH5zGCasGJLaEL0tzlJaeL8g5NCc10Vz95gZkGL flnZ', 'lstr': '297d9TOOY4f/a3FCsZg+kICVwpXav1+Wz55bi6+0MN96Pv2pZEsnpSgz8QSL1QQIoDYHGn3B5qsVrw9o0KRt', 'ltoken': '246c852f8a86519e52f90ff8728cc11e', 'realnameverifyemail': '0'}), None

**Comment by jingle0927** [comment]
![_ _20170821100500](https://user-images.githubusercontent.com/26103116/29501090-6cc03abc-8658-11e7-9e05-67dc64238983.png)
 貌似又有问题了

**Comment by Yufeikang** [comment]
百度经常调整webapi。建议大家使用pcs
