### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by JamesBr0wn** [Yufeikang/bcloud#5]
不知道为什么，我登录的时候总是提示未知错误，我用的系统是Ubuntu16.04.2LTS，望解答

**Comment by JamesBr0wn** [comment]
而且登录的时候也没有弹出验证码对话框，到底是哪里出了问题呢？

**Comment by Yufeikang** [comment]
贴一下log吧

**Comment by JamesBr0wn** [comment]
嗯不好意思可能是依赖的问题，我使用了一个网友打包的deb包后又可以用了😂
