### ISSUE TITLE
I can not log into my account \ 我无法登录我的帐户

### ISSUE THREAD

**Issue by seamail311** [Yufeikang/bcloud#73]
Hello, I can not log into your account through your program. How to fix the error? \ 您好，我無法通過您的計劃登錄您的帳戶。
![Снимок экрана_2019-05-29_12-49-54](https://user-images.githubusercontent.com/25530242/58547583-4f1e8a80-8210-11e9-9541-bf3eeefc5589.png)
![Снимок экрана_2019-05-29_12-44-54](https://user-images.githubusercontent.com/25530242/58547596-55ad0200-8210-11e9-9943-53719242ed91.png)

**Comment by yufeikang** [comment]
抱歉, 改项目目前停止维护
